version: '3.7'

services:
    app:
        image: symfony-app:local-dev
        ports:
            - '9000:9000'

    web:
        image: symfony-web:local-dev
        ports:
            - '8080:80'
        links:
            - app
